/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_incidents_get"];
        put?: never;
        /** Create Incident */
        post: operations["create_incident_incidents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Incident */
        get: operations["get_incident_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incident_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Incident Endpoint */
        post: operations["analyze_incident_endpoint_incidents__incident_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @example {
         *       "services": {},
         *       "status": "ok"
         *     }
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "unavailable";
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceHealth"];
            };
        };
        /** IncidentAnalyzeResponse */
        IncidentAnalyzeResponse: {
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            status: components["schemas"]["IncidentStatus"];
            /** Job Id */
            job_id: string;
            /** Queue Name */
            queue_name: string;
        };
        /** IncidentCreateRequest */
        IncidentCreateRequest: {
            /** Report Text */
            report_text: string;
            /** Language Hint */
            language_hint?: string | null;
            /** Location Hint */
            location_hint?: string | null;
        };
        /** IncidentDetailResponse */
        IncidentDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Text */
            original_text: string;
            /** Language Hint */
            language_hint: string | null;
            /** Detected Language */
            detected_language: string | null;
            /** Issue Type */
            issue_type: string | null;
            /** Severity */
            severity: string | null;
            status: components["schemas"]["IncidentStatus"];
            /** Confidence */
            confidence: string | null;
            /** Needs Review */
            needs_review: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Normalized Text */
            normalized_text: string | null;
            /** Extracted Location Text */
            extracted_location_text: string | null;
            /** Extracted Entities */
            extracted_entities: {
                [key: string]: unknown;
            };
            /** Brief Ka */
            brief_ka: string | null;
            /** Brief En */
            brief_en: string | null;
            /** Failure Details */
            failure_details: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** IncidentListResponse */
        IncidentListResponse: {
            /** Items */
            items: components["schemas"]["IncidentSummaryResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * IncidentStatus
         * @enum {string}
         */
        IncidentStatus: "created" | "queued" | "analyzing" | "analyzed" | "analysis_failed";
        /** IncidentSummaryResponse */
        IncidentSummaryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Original Text */
            original_text: string;
            /** Language Hint */
            language_hint: string | null;
            /** Detected Language */
            detected_language: string | null;
            /** Issue Type */
            issue_type: string | null;
            /** Severity */
            severity: string | null;
            status: components["schemas"]["IncidentStatus"];
            /** Confidence */
            confidence: string | null;
            /** Needs Review */
            needs_review: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ServiceHealth */
        ServiceHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded" | "unavailable";
            /** Detail */
            detail?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_incidents_incidents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_incident_incidents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentSummaryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_incident_endpoint_incidents__incident_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
